" Vim Configuration - Michael Sperone

" Start Pathogen
execute pathogen#infect()

set nocompatible
set number
set colorcolumn=80
"filetype plugin on

" Theme and Colors
colorscheme molokai

let g:monokai_term_italic = 1
let g:monokai_gui_italic = 1
set laststatus=2

" Terminal
set termwinsize=10x0

"  Spaces and Tabs
filetype plugin indent on
set tabstop=4
set shiftwidth=4
set expandtab
set autoindent
syntax on

" Searching
set hlsearch
set incsearch
" disable escape sequences (unused, slows down other functions)
set noesckeys

" Directory (netrw)
let g:netrw_keepdir = 0
let g:netrw_browse_split = 3
let g:netrw_altv = 1
" hilight marked files
hi! link netrwMarkFile Search

" Landscape View Setup
let g:netrw_banner = 0
let g:netrw_winsize = 20
"   liststyle - 1: wide (file info) | 3: tree
let g:netrw_liststyle = 1

" Portrait View Setup
" let g:netrw_windsize = 16
" let g:netrw_liststyle = 3

" Resize windows
set winheight=30

set splitbelow

" --- Finding Files ---
"   Recursive directory search, and tab completion
set path+=**
"   ignore node_modules folder
set wildignore+=**/node_modules/**
set wildignore+=**/node-offline-mirror/**
set wildignore+=**/node-packages/**
set wildignore+=**/.git/**
set wildignore+=**/.githooks/**
set wildignore+=**/.tmp/**
set wildignore+=**/.cache/**
set wildignore+=**/__mocks__/**
set wildignore+=**/virtual_env/**
set wildignore+=**/venv/**
set wildignore+=**/.venv/**
set wildignore+=*/tmp/*,*.so,*.swp,*.zip     " MacOSX/Linux
set wildignore+=*\\tmp\\*,*.swp,*.zip,*.exe  " Windows
"   display all matching files when tab completing
set wildmenu

" --- Remap Keys ---

" Moving Between Windows
"  Ctrl + h,j,k,l to move L, Dn, Up, R
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" tab autocomplete
" function! CleverTab()
"     if strpart( getline('.'), 0, col('.')-1 ) =~ '^\s*$'
"         return "\<Tab>"
"     else
"         return "\<C-N>"
"     endif
" endfunction
" inoremap <Tab> <C-R>=CleverTab()<CR>
" autocomple while typing (doesn't work)
" augroup myautocomp
"     au!
"     au TextChangedI * normal <C-R><C-N><CR>
" augroup END

"  F Keys
" <F2> set for UltiSnipsExpandTrigger
nnoremap <F3> :set hlsearch!<CR>
"     show relative numbers
nnoremap <F4> :set number relativenumber!<CR>
set nu rnu
"     code fold/unfold
nnoremap <F5> zc<CR>
nnoremap <F6> zo<CR>
"     move forward/backward in buffer
nnoremap <F7> :bp<CR>
nnoremap <F9> :bn<CR>
" or:
nnoremap <Home> :bp<CR>
nnoremap <End> :bn<CR>

nnoremap <F12> :SearchTasks src/**/*.*<CR>

autocmd BufNewFile,BufRead *.data,*.mjs,*.jsx set ft=javascript
autocmd BufNewFile,BufRead *.ts,*.tsx set ft=typescript
autocmd BufNewFile,BufRead *.ejs,*.nunj set ft=html


" Javascript code folding
set foldlevelstart=99
augroup javascript_folding
    au!
    au FileType javascript setlocal foldmethod=indent
augroup END

" ==== PLUGINS ====

" -- Git Gutter
"   https://github.com/airblade/vim-gitgutter
set updatetime=1000
let g:gitgutter_map_keys=0

" -- Syntastic
"   default setup, as recommended
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*i

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 1
" let g:javascript_plugin_jsdoc = 1

" --- Calendar ---
let g:calendar_google_calendar = 1
let g:calendar_google_task = 1

" --- Airline ---
set statusline+=%{gutentags#statusline()}

" --- UltiSnips ---
let g:UltiSnipsExpandTrigger="<return>"
let g:UltiSnipsEditSplit="vertical"

" --- SnipMate (no python) ---
let g:snipMate = { 'snippet_version' : 1 }

" --- TODO FIXME XXX ---

